# Generated by Django 2.1.2 on 2018-10-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
