# Generated by Django 2.1.2 on 2018-10-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181030_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WR', 'Work'), ('PR', 'Personal')], default='WR', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('LI', 'Limbo'), ('IP', 'In Progress'), ('CO', 'Complete')], default='IP', max_length=2),
        ),
    ]
