# Generated by Django 2.1.2 on 2018-10-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181031_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(null=True),
        ),
    ]
