# Generated by Django 2.1.2 on 2018-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20181031_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
