version: '3'

services:
  server:
    container_name: dev-sandbox_server
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: pipenv run gunicorn dev-sandbox.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.docker/.env
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - nginx_network
  nginx:
    container_name: dev-sandbox_proxy
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - nginx_network

volumes:
  static_volume:

networks:
  nginx_network:
    driver: bridge
