version: '3'

services:
  web:
    image: jcundiff/dev-sandbox:latest
    container_name: dev-sandbox
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: pipenv run gunicorn dev-sandbox.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - nginx_network
  nginx:
    image: nginx:latest
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  static_volume:

networks:
  nginx_network:
    driver: bridge
