# Generated by Django 2.1.2 on 2018-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_bio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.URLField(default='https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/44830491_10210156314184826_895943848826503168_n.jpg?_nc_cat=105&_nc_ht=scontent-atl3-1.xx&oh=a92eace7067ec74865a61baefb5015b2&oe=5C7B93C5'),
            preserve_default=False,
        ),
    ]
