# Generated by Django 2.1.2 on 2018-10-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_bio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='objective',
            field=models.BooleanField(default=True),
        ),
    ]
