version: '3'

services:
  server:
    image: dev-sandbox/server
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    command: pipenv run gunicorn dev-sandbox.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - nginx_network
  client:
    image: dev-sandbox/client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    args:
      - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
      - APP_GROUP=${APP_GROUP}
      - APP_GROUP_ID=${APP_GROUP_ID}
      - APP_USER=${APP_USER}
      - APP_USER_ID=${APP_USER_ID}
      - TARGET_PHP_VERSION=${PHP_VERSION}
      - TZ=${TIMEZONE}
    networks:
      - nginx_network
  nginx:
    image: nginx:latest
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  static_volume:

networks:
  nginx_network:
    driver: bridge
